name: Deployment pipeline

on:
    push:
        branches:
            - main

jobs:
    pipeline_deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: npm install
              run: npm install
            - name: npm start
              run: npm start
            - name: lint
              run: npm run eslint
            - name: depoloy to heroku
              if: ${{ github.event_name == 'push' }}
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'phonebook-nodejs'
                  heroku_email: 'rauhamaa.tomi@gmail.com'
                  healthcheck: 'https://phonebook-nodejs.herokuapp.com/health'
                  checkstring: 'OK'
                  delay: 5
                  rollbackonhealthcheckfailed: true
