name: Deployment pipeline

on:
    push:
        branches:
            - main

jobs:
    pipeline_deployment:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
            - name: npm install
              run: npm install
            - name: lint
              run: npm run lint
            - name: lint failed
              uses: rjstone/discord-webhook-notify@v1
              if: failure()
              with:
                  severity: error
                  details: Lint failed!
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            - name: deploy to heroku
              if: ${{ github.event_name == 'push' }}
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                  heroku_app_name: 'phonebook-nodejs'
                  heroku_email: 'rauhamaa.tomi@gmail.com'
                  healthcheck: 'https://phonebook-nodejs.herokuapp.com/health'
                  checkstring: 'OK'
                  delay: 5
                  rollbackonhealthcheckfailed: true
    tag_release:
        needs: [pipeline_deployment]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: '0'
            - name: Bump version and push tag
              if: ${{ github.event_name == 'push' }}
              uses: anothrNick/github-tag-action@1.36.0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  DEFAULT_BUMP: patch
                  WITH_V: false
                  DRY_RUN: true
            - name: version deployed
              uses: rjstone/discord-webhook-notify@v1
              if: success()
              with:
                  severity: info
                  details: Version deploy succeeded!
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
